# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: importer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'importer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dep_pb2 as dep__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eimporter.proto\x12\x08tutorial\x1a\tdep.proto\"&\n\x08Importer\x12\x1a\n\x03\x64\x65p\x18\x01 \x01(\x0b\x32\r.tutorial.Depb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'importer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMPORTER']._serialized_start=39
  _globals['_IMPORTER']._serialized_end=77
# @@protoc_insertion_point(module_scope)
